# Generated by Django 5.0.4 on 2024-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rowCount',
            field=models.IntegerField(default=50),
        ),
    ]
