# Generated by Django 5.0.4 on 2024-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseGen', '0002_table_rowcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='rowCount',
            field=models.IntegerField(null=True),
        ),
    ]
