# Generated by Django 5.0.4 on 2024-07-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseGen', '0003_association_rowcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='rowCount',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
