# Generated by Django 5.0.4 on 2024-07-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseGen', '0004_alter_association_rowcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='type',
        ),
        migrations.AddField(
            model_name='field',
            name='dataType',
            field=models.CharField(default='TEXT', max_length=8),
        ),
    ]
